### ISSUE TITLE
ISIC experiment

### ISSUE THREAD

**Issue by VietHoang1512** [Wuyxin/DISC#2]
Hi @Wuyxin, thank you for sharing your great work.

I run the GroupDRO and other methods on the ISIC dataset. Could you please explain more about the way you pick the model for evaluating on the test set (e.g. based on validation's AUC or worst group)?

**Comment by VietHoang1512** [comment]
Also, did you set `id_val=True` [here](https://github.com/Wuyxin/DISC/blob/master/disc/dataset/isic_dataset.py#L60) for a more stable training and consistent comparison across baselines?

**Comment by Wuyxin** [comment]
Hi!

Thanks for the questions!

We pick the model by the validation's AUC ([https://github.com/Wuyxin/DISC/blob/master/disc/train.py#L215](https://github.com/Wuyxin/DISC/blob/master/disc/train.py#L215)) since the group size is 2^7 considering combinations of spurious attributes, which results in many small groups. Thus we compute the average AUROC score across the train-test splits, as standard in Bissoto et al. (2020).

Yes! We use `id_val=True`. 

Let me know if you have more questions!

**Comment by VietHoang1512** [comment]
Thank you so much for your instant response! It helped me a lot.
